--create..

--normalde tables sað tik new table vs derdik kod ile create sayesinde oluþtururuz
--CREATE TABLE <TABLOADI> (KOLON1 TÝP1,KOLON2 TÝP2.....)

--CREATE TABLE CUSTOMERS(ID INT,TCNUMBER VARCHAR(15),....)

--NORMALDE MANUEL OLUÞTURURKEN TABLOYU ID'YI OTOMATÝK ARTAN YAPIYORDUK BURDA NASIL YAPACAZ?
--IDENTITY(1,1) EKLE YANINA
--CREATE TABLE CUSTOMERS(ID INT IDENTITY(1,1),TCNUMBER VARCHAR(15),....)


--PRIMARY KEY DE OLSUN ÝSTERSEN YANINA EKLERSÝN PRIMAR KEY DÝYE
--CREATE TABLE CUSTOMERS(ID INT IDENTITY(1,1) PRIMARY KEY,TCNUMBER VARCHAR(15),....)

--NORMALDE ELÝNLE ALLOW NULLS KONTROLÜ YAPABÝLÝRSÝN EÐER KODDA YAPMAK ÝSTERSEN YANINA NOT NULL EKLE
--CREATE TABLE CUSTOMERS(ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,TCNUMBER VARCHAR(15),....)
