--drop
--tabloyu tamamen uçurur ,yok eder

--DROP TABLE TABLOADI

--PEKÝ DELETE VE TRUNCATE'DEN FARKI NE ?
--DELETE VE TRUNCATE FARKINI KONUÞMUÞTUK DELETE DE WHERE VARDI VE DELETE ÝLE SÝLÝNCE ID SÝLÝNEN SAYIDAN DEVAM EDERDÝ 1 DEN DEÐÝL
--TEKRAR EKLEYÝNCE
--BUNLARDA SÜTUN ÝSMÝ KALIR SÝLSENDE
--FAKAT DROP KOMPLE HER ÞEYÝ UÇURUYOR SANKÝ O TABLO HÝÇ YOKMUÞ GÝBÝ