--truncate
--TRUNCATE TABLE TABLOADI
SELECT * FROM CUSTOMERS
--TRUNCATE TABLE CUSTOMERS

--DELETE FROM CUSTOMERS DAN FARKI ÞU DELETE ÝLE TABLOYU SÝLÝNCE 
--TEKRAR KAYIT ATTIÐINDA IDLER 1 DEN BAÞLAMAZ TABLOYU ÝLK HALÝNE ÇEVÝRMÝYOR 960 KAYÝT VARSA
--961 DEN DEVAM EDER 
--TRUNCATE DE BÖYLE DEÐÝL TABLOYU HÝÇ DOLDURULMAMIÞ GÝBÝ ÝLK HALÝNE ÇEVÝRÝR BOÞALTIR....


--BÝR DÝÐER DELETE VE TRUNCATE FARKÝ ÞU DELETEDE WHERE KULLANABÝLÝYORDUK KOÞULLU SÝLEBÝLÝRÝZ
--FAKAT TRUNCATEDE KOÞUL YOK DÝREKT BOÞALTÝR TABLOYU