--DISTINCT
SELECT * FROM CUSTOMERS
DELETE FROM CUSTOMERS WHERE TELOPERATOR2
--TEKRAR EDEN VERÝLERÝ TEKÝLLESTÝRMEK AMACÝ ÝLE KULLANiLiR
--SELECT ÝLE BÝRLÝKTE KULLANÝLÝYOR

--SELECT DISTINCT ID ,TCNUMBER FROM CUSTOMERS WHERE........
SELECT DISTINCT CITYID FROM CUSTOMERS
SELECT DISTINCT CITYID,DISTRICTID FROM CUSTOMERS WHERE CITYID ='34'
