--EXAMPLES1
--ÖNCE SELECT AVGLÝ FROM TABLOADI SONRA VARSA WHERE
--SONRA GROUP BY SONRA HAVÝNG ÝSTERSEN SONA ORDER BY

SELECT * FROM SALES
--1--AGGLER YANINDAKÝ ÝSÝMLENDÝRME OLMAK ZORUNDA DEÐÝL AMA AMAÇ ÝSÝMLENDÝRME YAPMAK
SELECT COUNT(*) SATIRSAYISI,SUM(TOTALPRICE)CIRO,
SUM(AMOUNT)TOPLAMADET,MIN(PRICE) ENDUSUKFIYAT,
MAX(PRICE) ENYUKSEKFIYAT,
AVG(PRICE) ORTALAMAFIYAT
FROM SALES

WHERE CITY='ÝSTANBUL'

--2--NORMAL SÜTUN YAZAMAZDIK AGGLÝ SÜTUN VARSA YA HEPSÝ AGG ÝÇÝNDE OLACAKTI YA DA DÜZ OLANI GROUP BY YAPACAKTIK
SELECT CITY SEHÝR,SUM(TOTALPRICE) CIRO
FROM SALES
GROUP BY CITY
ORDER BY CITY 
--3--OKUMAYI DA ÖÐREN BAK REGION CITY VE TOTALPRICE SÜTUNLARI GELECEK ÝSÝM VERÝLMÝÞ
--AYRICA DÜZ OLAN SÜTUNLAR GROUP BY A ALINMIÞ KIRILIM ONLARA GÖRE OLACAK
--SIRALAMA YAPACAK REGIONA GÖRE
SELECT REGION BOLGE,CITY SEHÝR,
SUM(TOTALPRICE) CIRO FROM SALES
GROUP BY REGION,CITY
ORDER BY REGION

--4--BÝR MAÐAZANIN GÜN BAZLI SATIÞLARI
--TABLODAKÝ DATE ALANININ SADECE TARÝH KISMINI ALMAK ÝÇÝN
--SQL DE CONVERT VAR 
--CONVERT(SÜTUN TÝPÝ,SÜTUNADI)
SELECT CONVERT(DATE,DATE_) TARIH,SUM(TOTALPRICE)CIRO
FROM SALES
GROUP BY CONVERT(DATE,DATE_)
ORDER BY CONVERT(DATE,DATE_)

--5--BÝR GÜNÜN MAÐAZA BAZLI SATIÞLARINI GETÝRME
--ÖNCE BÝR GÜN SEÇELÝM TABLODAN
SELECT CITY SEHÝR,SUM(TOTALPRICE) CIRO
FROM SALES
WHERE DATE_ BETWEEN '2019-08-02 00:00:00' AND '2019-08-02 23:59:59'
GROUP BY CITY

--6--BELÝRLÝ BÝR CÝRONUN ÜSTÜNDE SATIÞ YAPAN MAÐAZALAR
--WHERE-HAVING FARKI ?
SELECT CITY SEHÝR,SUM(TOTALPRICE) CIRO
FROM SALES
GROUP BY CITY
HAVING SUM(TOTALPRICE)>100000
ORDER BY CITY

--7--MAÐAZANIN AYLARA GÖRE SATIÞLARINI GETÝRME
--ÞEHÝR GELECEK AY GELECEK CIRO GELECEK
--AY ÝSMÝ GETÝRMEK ÝÇÝN DATEPART(MONTH,SÜTUNADI) KOMUTU OLMALI
SELECT CITY SEHÝR,DATEPART(MONTH,DATE_) AY,
SUM(TOTALPRICE) CIRO
FROM SALES
GROUP BY CITY,DATEPART(MONTH,DATE_)
ORDER BY CITY,DATEPART(MONTH,DATE_)

--8--ÜRÜN KATEGORILERÝNE GÖRE SATIÞLARI GETÝRME
SELECT CATEGORY1 KATEGORI1,CATEGORY2 KATEGORI2,
SUM(TOTALPRICE) CIRO FROM SALES
GROUP BY CATEGORY1,CATEGORY2
ORDER BY CATEGORY1 ASC,SUM(TOTALPRICE) DESC
--DÝYOR KÝ OKUMAYI DA ÖÐREN...
--CAT 1 VE CAT 2 YÝ GETÝR SÜTUN OLARAK TOPLAM SATIÞI GETÝR SÜTUN OLARAK
--AYRICA GROUP BY A ALINMIÞ ÇÜNKÜ DÜZ SUTUNLAR
--AYRICA CAT1 Ý DÜZ SIRALA AMA CAT 2 YÝ TOPLAM SATIÞTA TERSTEN SIRALA DEMÝÞ

--9--MAÐAZALARIN *TEKÝL* MÜÞTERÝ SAYILARINI GETÝRME
--DÝSTÝINCT OLMADAN YAPARSAN AYNI MÜÞTERÝLER GELÝR DÝSTÝNCT TEKÝLLEÞTÝRME YAPARDI
--COUNT(DÝSTÝNCT(CUSTOMERCODE))
--ÖNCE CUSTOMER KODU TEKÝLLEÞTÝR SONRA SAY DEDÝK

--YANÝ COUNT VE COUNT(DISTINCT()) FARKINI ANLA BÝRÝ TÜM SAYIYI GETÝRÝR DÝÐERÝ AYNI KAYDI 1KERE SAYAR GETÝRÝR
SELECT CITY SEHÝR,COUNT(DISTINCT(CUSTOMERCODE)) MUSTERISAYISI
FROM SALES
GROUP BY CITY
ORDER BY CITY