-----------------------------------example2-----------------------------------
--agg,group by,having ve joýn mantýklarýný bol bol kullanacaðýz 
--önceki örneklerden farký iliþkili tablolar üzerinde çalýþacaðýz önce tek bir tablo ile çalýþýyorduk artýk join biliyoruz
SELECT * FROM INVOICES

--þehirlere göre sipariþleri toplam olarak listeleme
SELECT CT.CITY SEHÝR,SUM(O.TOTALPRICE) SÝPARÝSTUTARI,COUNT(O.ID) SIPARISSAYISI 
FROM ORDERS O--ZATEN SÝPARÝÞLERÝ ÇEKTÝK ORDERS TABLOSUNDAN FAKAT ÞEHÝR KALDI ONUN ÝÇÝN DE ÖNCE ADRESE SONRA ÞEHÝRE GÝDECEZ
JOIN ADDRESS A ON A.ID=O.ADDRESSID--ÖNCE ADRES TABLOSUNA GELDÝK ORDAN ADRES ÝLE ÝLÝÞKÝLÝ ÞEHÝR TABLOSUNA GELECEÐÝZ
JOIN CITIES CT ON CT.ID=A.CITYID

GROUP BY CT.CITY

--SÝPARÝÞLERÝN ORTALAMA KARGO SÜRELERÝNÝ(FATURANIN KESÝLME TARÝHÝ-ÝNVOÝCE DE DATE) GETÝRME
--ORDERS TABLOSUNDAKÝ DATE ALANI ÝLE INVOICE ARASINDAKÝ FARKI ALDIK ORTALAMASINI
SELECT CT.CITY SEHÝR ,AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) HAZIRLIKSURESÝ
FROM ORDERS O

JOIN INVOICES I ON I.ORDERID=O.ID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES CT ON CT.ID=A.CITYID

GROUP BY CT.CITY

--yaþ gruplarýna göre sipariþ daðýlýmý
--YAÞLA ÝLGÝLÝ YER USERS TABLOSUNDA VAR BIRTHDATE VAR BUGÜNDEN ÇIKARIR HESAPLARSIN DOÐRUDAN YOK ÇÜNKÜ
--DEMEKKÝ ÇIKIÞ NOKTAMIZ USERS TABLOSU ORDAN DOÐRUDAN YAÞ BÝLGÝSÝ YOK DEDÝÐÝM GÝBÝ GÝDECEZ
SELECT DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) YAS, 
SUM(O.TOTALPRICE) SIPARISTOPLAMI
FROM USERS U
JOIN ORDERS O ON U.ID=O.USERID

GROUP BY DATEDIFF(YEAR,U.BIRTHDATE,GETDATE())
ORDER BY DATEDIFF(YEAR,U.BIRTHDATE,GETDATE())
--BU VERÝR AMA YAÞLARI GRUP OLARAK ÝSTEMÝÞ SORU 20-30 YAÞ GÝBÝ ONU VERMEZ
--BU YAPIYI CASE-WHEN ÝLE YAPABÝLÝRÝZ BU ÝF-ELSE MANTIÐI ÝLE AYNI    
--20 ÝLE 30 YAÞ ARASINI 20-30 
--30 ÝLE 40 YAÞ ARASINI 30-40 DÝYE BÖYLE KATEGORÝZE EDECEK.
SELECT DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) YAS,
CASE 
    WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 20 AND 30 THEN '20-30 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 31 AND 40 THEN '31-40 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 41 AND 50 THEN '41-50 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 51 AND 60 THEN '51-60 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 61 AND 70 THEN '61-70 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 71 AND 80 THEN '71-80 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) >80  THEN '80-90 YAÞ ARASI'
END AS YASARALIGI,
SUM(O.TOTALPRICE) SIPARISTOPLAMI
FROM USERS U
JOIN ORDERS O ON U.ID=O.USERID

GROUP BY DATEDIFF(YEAR,U.BIRTHDATE,GETDATE())
ORDER BY DATEDIFF(YEAR,U.BIRTHDATE,GETDATE())

--GROUP BY YANINA DATEDIFF SÝLÝP CASE WHEN BLOÐUNU YAPIÞTIRIRSAN TÜM GRUPLARI TEK KAYIT HALÝNE DE GETÝREBÝLÝRSÝN
SELECT --DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) YAS,
CASE 
    WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 20 AND 30 THEN '20-30 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 31 AND 40 THEN '31-40 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 41 AND 50 THEN '41-50 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 51 AND 60 THEN '51-60 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 61 AND 70 THEN '61-70 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 71 AND 80 THEN '71-80 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) >80  THEN '80-90 YAÞ ARASI'
END AS YASARALIGI,
SUM(O.TOTALPRICE) SIPARISTOPLAMI
FROM USERS U
JOIN ORDERS O ON U.ID=O.USERID

GROUP BY
CASE 
    WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 20 AND 30 THEN '20-30 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 31 AND 40 THEN '31-40 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 41 AND 50 THEN '41-50 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 51 AND 60 THEN '51-60 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 61 AND 70 THEN '61-70 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 71 AND 80 THEN '71-80 YAÞ ARASI'
	WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) >80  THEN '80-90 YAÞ ARASI'
END
ORDER BY 1

--ÜRÜN ANALÝZÝ(ÝLK SATIÞ TARÝHÝ-SONSATIÞTARÝHÝ,EN YÜKSEK FÝYATI VS VS)
SELECT I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA,
I.CATEGORY1 KATEGORI1,I.CATEGORY2 KATEGORI2,
MIN(O.DATE_) ILKSATISTARÝHÝ,MAX(O.DATE_) SONSATISTARIHI,
MIN(OD.UNITPRICE) ENDUSUKFÝYAT,MAX(OD.UNITPRICE) ENYUKSEKFIYAT,
AVG(OD.UNITPRICE) ORTALAMAFIYAT,SUM(OD.LINETOTAL) CIRO
FROM ITEMS I
JOIN ORDERDETAILS OD ON I.ID=OD.ITEMID
JOIN ORDERS O ON O.ID=OD.ORDERID

GROUP BY I.ITEMCODE ,I.ITEMNAME ,I.BRAND ,
I.CATEGORY1 ,I.CATEGORY2
