--HAVÝNG 
--GRUPLAMA(GROUP BY) SONRASI FÝLTRELEME ÝÇÝN KULLANILIR 
--GROUP BY DEN SONRA KULLANILIR 
--WHERE TEK TEK BAKAR VE GRUPLAMA(GROUP BY) ÖNCESÝ FÝLTRELER HAVÝNG ÝSE TÜM SONUCA BAKIP FÝLTRELER GRUPLAMA(GROUP BY) SONRASI FÝLTRELER
--UNUTMA GROUP BY VARSA HAVÝNG KULLANABÝLÝRSÝN

SELECT CITY SEHÝR,SUM(TOTALPRICE) CIRO
FROM SALES 
GROUP BY CITY
HAVING SUM(TOTALPRICE)>100000
ORDER BY SUM(TOTALPRICE)
SELECT * FROM SALES
