--ORDER BY

--SELECT KOLON1,KOLON2.... FROM TABLOADI WHERE ÞARTLAR ORDER BY KOLON1.... (BAÞI ZATEN SELECT SYNTAX)
SELECT * FROM CUSTOMERS

SELECT * FROM CUSTOMERS WHERE CITYID LIKE '%1%' ORDER BY CITYID

SELECT * FROM CUSTOMERS ORDER BY NAMESURNAME ASC--ASC OLMADAN DA OLUR

SELECT * FROM CUSTOMERS ORDER BY CITYID,NAMESURNAME

SELECT * FROM CUSTOMERS ORDER BY CITYID,DISTRICT,GENDER DESC -- CITYID GÖRE NORMAL SIRALA
--DISTRICT GÖRE NORMAL SIRALA
--GENDERA GÖRE TERSTEN SIRALA

--ORDER BY ÝLE SADECE KOLON ADINA GÖRE SIRALAMA YAPILMAZ
--ORDER BY CITYID DEDÝK MESELA BAK TABLONA CITYID KAÇINCI SÜTUN 7 ORDER BY 7 DÝYEBÝLÝRSÝN
