--------------------------------------ÝLÝÞKÝSEL VERÝ TABANI BÖLÜMÜ--------------------------------------
--RDMS NEDÝR ?
--PRÝMARY KEY FOREÝGN KEY KAVRAMLARI ??

--iliþkisel bir veritabaný oluþturmak elle sað týk ile ? ve içine veri girmek??

--iliþkisel bir veri tabanýndan nasýl veri çekilir ??
--1-)SELECT MANTIÐI ÝLE = ÇOK KULLANILMAZ ÇÜNKÜ JOÝNLER VAR ÝLERDE GÖRECEÐÝZ AMA BÝL

SELECT U.USERNAME_,U.NAMESURNAME,U.EMAIL,U.BIRTHDATE,A.ADDRESSTEXT,A.POSTALCODE,C.COUNTRY,
CT.CITY
FROM USERS U,ADDRESS A,COUNTRIES C,CITIES CT
WHERE U.ID=A.USERID
AND C.ID=A.COUNTRYID
AND CT.ID=A.CITYID

--2-)JOÝN KAVRAMI
--almak istediðimiz tüm deðerler adres tablosuna baðlý þemada da belli o yüzden A. hep
--BAKACAKSIN JOIN CITIES YAPTIN MESELA SANA NE LAZIM O TABLODAN CITY LAZIM BAK O TABLOYA GÝBÝ GÝBÝ DÜÞÜN
--baktýðýn iki tablonun iliþkili yeri kýsaca pk=fk mantýðýyla 
SELECT U.USERNAME_,U.NAMESURNAME,U.EMAIL,U.BIRTHDATE
,A.ADDRESSTEXT,A.POSTALCODE,
C.COUNTRY,CT.CITY,T.TOWN,D.DISTRICT
FROM USERS U
JOIN ADDRESS A ON U.ID=A.USERID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID--MESELA DÝYOR KÝ ADRES TABLOSUNDAKÝ COUNRTYID YERÝNE C YANÝ COUNTRÝES'DEKÝ ID KARÞILIÐINI GETÝR DÝYOR BÖYLE OKU DÜÞÜN
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID 

--BAZI TABLOLARI MANUEL OLARAK SAÐ CLÝCK YÖNTEMÝYLE OLUÞTURDUK BUNDAN ÖNCE
--FAKAT ÞÝMDÝ KALAN TABLOLARI SCRÝPT YANÝ KOD YAZARAK OLUÞTURACAZ
--BÖYLECE SCRÝPT ÝLE(DDL COMMANDS) NASIL ÝLÝÞKÝSEL VERÝTABANI OLUÞTURACAZ ONU GÖRECEÐÝZ
--orders tablosunu yapalým mesela...
CREATE TABLE ORDERS(ID INT IDENTITY(1,1),
USERID INT,
DATE_ DATETIME,
TOTALPRICE FLOAT,
STATUS_ TINYINT,
ADRESSID INT)
--ÝNVOÝCE TABLOSUNU OLUÞTURALIM...
CREATE TABLE INVOICE(ID INT IDENTITY(1,1),
ORDERID INT,
DATE_ DATETIME,
ADDRESSID INT,
CARGOFICHENO VARCHAR(20),
TOTALPRICE FLOAT)
--INVOICEDETAIL TABLOSU...
CREATE TABLE INVOICEDETAIL(
ID INT IDENTITY(1,1),
INVOICEID INT,
ORDERDETAILID INT,
ITEMID INT,
AMOUNT INT,
UNITPRICE FLOAT,
LINETOTAL FLOAT)
--ORDERDETAILS TABLOSU
CREATE TABLE ORDERDETAILS(
ID INT IDENTITY(1,1),
ORDERID INT,
ITEMID INT,
AMOUNT INT,
UNITPRICE FLOAT,
LINETOTAL FLOAT)
--ITEMS TABLOSU
CREATE TABLE ITEMS(
ID INT IDENTITY(1,1),
ITEMCODE VARCHAR(50),
ITEMNAME VARCHAR(100),
UNITPRICE FLOAT,
CATEGORY1 VARCHAR(50),
CATEGORY2 VARCHAR(50),
CATEGORY3 VARCHAR(50),
CATEGORY4 VARCHAR(50),
BRAND VARCHAR(50))
--PAYMENTS TABLOSU
CREATE TABLE PAYMENTS(
ID INT IDENTITY(1,1),
ORDERID INT,
PAYMENTTYPE TINYINT,
DATE_ DATETIME,
ISOK BIT,
APPROVECODE VARCHAR(100),
PAYMENTTOTAL FLOAT)

--INSERT ÝLE VERÝ EKLEYEBÝLÝRÝZ TABLOLAR BOÞ FAKAT BÝZDE HAZIR DOLU VAR ONU ÝNDÝRÝP DAHÝL EDELÝM
SELECT * FROM ORDERS--BU TABLOYA BAKTIÐINDA(ANA TABLO BU ÇÜNKÜ) USERID VE ADDRESSID DÝYE 2 YER VAR DEMEKKÝ ONLAR DÝÐER TABLOLARLA ÝLÝÞKÝLÝ BÖYLE OKU
--DEMEKKÝ BU ORDERS TABLOSUNA JOIN YAPACAZ USERS VE ADDRESS TABLOSUNU(USERID VE ADRESSID OLDUÐU ÝÇÝN)

--ORDERS TABLOSUNDAN ID VE DATE KISIMLARI ALALIM ALÝAS VERELÝM VE DEDÝÐÝMÝZ GÝBÝ JOINLERÝNÝ YAPALIM...
SELECT O.ID SÝPARÝSID,O.DATE_ SÝPARÝSTARÝH,
U.USERNAME_,U.NAMESURNAME,U.EMAIL,
A.ADDRESSTEXT,A.POSTALCODE,
C.COUNTRY,
CT.CITY,
T.TOWN,
D.DISTRICT,
OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL,
I.ITEMNAME,I.ITEMCODE
FROM ORDERS O
JOIN USERS U ON U.ID=O.USERID--ON SONRASI MANTIK ÞU ORDERS TABLOSUNDA USERID YERÝNE USERS TABLOSUNDA ID NÝN KARÞILIÐI GELSÝN
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID--ADRES TABLOSUNDA COUNTRY ID YERÝNDE NUMARA VAR ONUN YERÝNE COUNTRIES TABLOSUNDA ID KARÞILIÐI OLAN ÞEHRÝ GETÝRSÝN
JOIN CITIES CT ON  CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID

WHERE O.ID =1

--MESELA BÝZ JOINLERDE ON KISIMLARINI YAZARKEN ÝLÝÞKÝLERÝ KENDÝMÝZ BÝLÝYORUZ 
--MSSQL BÝZE SÖYLEMÝYOR 
--FAKAT VERÝTABANI BAZINDA ÝLÝÞKÝ OLUÞTURABÝLÝRÝZ DATABASEMÝZE GEL DÝAGRAMA TIKLA MESELA USERS VE ADRESS TABLOSUNU EKLE
--NASIL ÝLÝÞKÝ VAR ARALARINDA USERSTAKÝ ID ADRESTEKÝ USERID ASLINDA TUT SÜRÜKLE
--amaç veri bütünlüðünü korumak ve tasarýmý düzenli hale getirmek bunu yaparken.


--JOIN TÜRLERÝ
-- 2 adet iliþkili tabloyu alalým
-- users ve address 
-- bu 2 tablo üstünden önce kodsuz inner join,left join,right join,full join kavramlarý ??

--join türleri uygulama...
--NORMAL JOÝN YAPISI BU AYNI ZAMANDA DÝÐER ADI INNER JOÝN
SELECT U.USERNAME_,A.USERID,A.CITYID
FROM USERS U
JOIN ADDRESS A ON U.ID=A.USERID
--INNER DE YAZABÝLÝRSÝN SONUÇ DEÐÝÞMEZ
SELECT U.USERNAME_,A.USERID,A.CITYID
FROM USERS U
INNER JOIN ADDRESS A ON U.ID=A.USERID
--LEFT JOIN--BAÞA LEFT YAZARSIN SADECE
SELECT U.USERNAME_,A.USERID,A.CITYID
FROM USERS U
LEFT JOIN ADDRESS A ON U.ID=A.USERID
--RIGHT JOIN BAÞA RIGHT YAZARSIN SADECE
SELECT U.USERNAME_,A.USERID,A.CITYID
FROM USERS U
RIGHT JOIN ADDRESS A ON U.ID=A.USERID
--FULL JOIN
SELECT U.USERNAME_,A.USERID,A.CITYID
FROM USERS U
FULL JOIN ADDRESS A ON U.ID=A.USERID

--NOT-> LEFT RIGHT OLAYI JOIN KELÝMESÝNÝN ÖNCESÝNDEKÝ TABLO LEFT YANÝ SOL KÜME
--JOIN KELÝMESÝ SONRASINDAKÝ TABLO RÝGHT YANÝ SAÐ KÜMEDÝR
--NORMALDE ON SONRASI = SAÐI SOLU OLARAK BÝLÝNÝR O YANLIÞTIR....


--SUBQUERY NEDÝR ??
--alt sorgu anlamýna gelir ve iç içe sorgu yazmaktýr aslýnda 
--join varken kullanmak hem hýz hem de karmaþýklýk açýsýndan doðru deðil fakat
--bazý sorular var ki subquery olmadan cevap bulunmuyor

--hangi müþteri kaç kez sipariþ vermiþ ?? joýn ile
SELECT U.ID,U.NAMESURNAME,SUM(O.TOTALPRICE),COUNT(O.USERID)
FROM USERS U
JOIN ORDERS O ON U.ID=O.USERID
GROUP BY U.ID,U.NAMESURNAME

--subquery ile
SELECT U.ID,U.NAMESURNAME, 
(SELECT COUNT(*) FROM ORDERS WHERE USERID=U.ID)
FROM USERS U