--TOP
--BELÝRLÝ SAYÝDA SATÝR GETÝRÝR

SELECT TOP 5 * FROM CUSTOMERS 
SELECT TOP 50 * FROM CUSTOMERS  ORDER BY CITYID DESC

SELECT TOP 10 * FROM CUSTOMERS WHERE CITYID='34' ORDER BY AGE

--PERCENT TOPLAM SAYININ YÜZDELÝK OLARAK GETÝR DER
--AÞAÐIDA ÖRNEK VAR CUSTOMERS TABLOSUNDAKÝ TOPLAM KAYIDIN YÜZDE 5 ÝNÝ GETÝR DÝYOR PERCENT ÝLE
SELECT TOP 5 PERCENT * FROM CUSTOMERS 