--where and operators

--operators(=,<>,<,>,<=,>=,IN,NOT IN,LÝKE,NOT LÝKE,BETWEEN,AND,OR)
--where özel syntaxý yok komutlarla kullanýmý üzerinde duracaðýz(ddl-dml)
--GENELDE (1)where kelimesi sonra (2)sütun adý sonra (3)operatör gelir sýralama budur
--örnek...
SELECT * FROM CUSTOMERS WHERE CITYID >=70
SELECT * FROM CUSTOMERS WHERE CITYID = 40
SELECT * FROM CUSTOMERS WHERE NAMESURNAME='TUÐÇE AKKOÇ'
SELECT * FROM CUSTOMERS WHERE NOT CITYID = 20--GENEL DIÞI KULLANIM MESELA HEP ÖYLE OLMAZ DEDÝGÝMÝZ GÝBÝ
--NOT OLAN SORGULARI ÖNCE DÜZ YAZ SONRA NOT NEREYE GELÝR DAHA ANLASÝLÝR OLUYOR


--BETWEEN
SELECT *FROM CUSTOMERS WHERE ID BETWEEN 2 AND 10
SELECT *FROM CUSTOMERS WHERE EMAIL BETWEEN 'A' AND 'D'


--IN
SELECT * FROM CUSTOMERS WHERE CITYID IN (2,3,4,5,6)--direkt diyor ki id bu olanlarý getir
--SELECT * FROM CUSTOMERS WHERE CITY IN ('ANKARA','ÝSTANBUL')--þehri bu olanlarý getir diyor
--customers tablosunu seç þehri ankara istanbul içinde olanlarý getir demek þehri bu olanlarý getir demek zaten

--LIKE-NOTLIKE
SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE 'ALÝ%'
SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE '%ALÝ'
SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE '%ALÝ%'
SELECT * FROM CUSTOMERS WHERE NAMESURNAME NOT LIKE 'ALÝ%'

--AND / OR
SELECT * FROM CUSTOMERS WHERE CITYID = '34' AND AGE = '30'
SELECT * FROM CUSTOMERS WHERE CITYID='34' AND GENDER='E'
SELECT * FROM CUSTOMERS WHERE CITYID = '34' AND AGE = '30' OR AGE = '25'
SELECT * FROM CUSTOMERS WHERE CITYID = '34' OR CITYID='35' OR CITYID='6'--SELECT * FROM CUSTOMERS WHERE CITYID IN ('ISTANBUL','ANKARA','ÝZMÝR') AYNISI
SELECT * FROM CUSTOMERS WHERE CITYID='34' AND (DISTRICT='AVCILAR' OR GENDER = 'E')--SELECT * FROM CUSTOMERS WHERE CITYID='34' AND DISTRICT='AVCILAR' OR GENDER = 'E' PARANTEZÝN ÖNEMÝ


--WHERE KOMUTUNUN UPDATE VE DELETE ÝLE KULLANIMI
--UPDATE CUSTOMERS SET COUNTRY='TÜRKÝYE'
UPDATE CUSTOMERS SET TELOPERATOR1='X OPERATORU' WHERE TELNR1 LIKE '(53%'
UPDATE CUSTOMERS SET TELOPERATOR1='X OPERATORU' WHERE TELNR1 LIKE '(54%'
UPDATE CUSTOMERS SET TELOPERATOR1='Y OPERATORU' WHERE TELNR1 LIKE '(55%'
UPDATE CUSTOMERS SET TELOPERATOR1='Y OPERATORU' WHERE TELNR1 LIKE '(50%'
--DELETE FROM CUSTOMERS WHERE ID='2' ...... 

