--TRUNCATE KOMUTU
--ÝLGÝLÝ TABLONUN ÝÇÝNÝ BOÞALTÝR
--DELETEDEN BÝRÝNCÝ FARKÝ WHERE ÞARTÝ YOKTUR BURDA
--DÝÐER FARK SÝLME YAPÝLDÝGÝNDA ÝDENTTY YANÝ OTOMATÝK ARTAN KÝSÝM VARSA BURDA DELETE GÝBÝ SÝLÝNEN ÝD'DEN BAÞLAMAZ 1'DEN BAÞLAR TEKRARDAN

TRUNCATE TABLE CUSTOMERS--CUSTOMERS TABLOSUNUN ÝÇÝNÝ BOÞALTÝR

INSERT INTO CUSTOMERS(NAMESURNAME, GENDER, BIRTHDATE, CITY, TOWN, TELNR, TCNO)
VALUES ('OMER COLAK','E','1990-01-01','HATAY','XXX','05434526161','64281299212')--YENÝ KAYIT EKLEDÝK TABLOYA