--DELETE
--DELETE FROM TABLOADI WHERE<SARTLAR>
--DELETE FROM CUSTOMERS / CUSTOMERS TABLOSUNDAKÝ TÜM KAYITLARI SÝLER
SELECT * FROM CUSTOMERS


--ÖRNEK VERELÝM...

--DELETE FROM CUSTOMERS
--WHERE CITYID >50  AND GENDER='K';
