--update
--UPDATE TABLOADI SET KOLON1=DEGER1,KOLON2=DEGER2.... WHERE<SARTLAR>
SELECT * FROM CUSTOMERS

UPDATE CUSTOMERS SET COUNTRY = 'TÜRKÝYE'

SELECT DATEDIFF(YEAR,'1964-05-12','2025-07-19')--2 TARÝH ARASINDAKÝ FARKI YIL BAZLI ALDIK DATEDIFFLE.

UPDATE CUSTOMERS SET AGE = DATEDIFF(YEAR,BIRHTDATE,'2025-07-19')--herkesin yaþýný dinamik olarak güncelledik.

